packages:
  - 'packages/*'
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - arm64
  libc:
    - current
    - glibc
allowBuilds:
  esbuild: true
  tree-sitter-css: true
  tree-sitter-html: true
  tree-sitter-javascript: true
