import type { GrammarId, ZoneSplitter } from '@codegraft/core'

/**
 * Emit an ES module for a codemod target. A codemod body is param-rooted — everything hangs off
 * the `root`/`context` arguments — so its `.toString()` is self-contained: the generated module
 * imports only `createCodemodTransformer` (plus a splitter), then passes the body verbatim.
 */
export function serialiseCodemod(target: GrammarId | ZoneSplitter, body: string, namespace?: string): string {
  const splitter = typeof target === 'string' ? null : target
  const imports = [`import { createCodemodTransformer } from '@codegraft/core'`]
  let targetExpr: string
  if (splitter) {
    if (!splitter.importName || !splitter.importPath) {
      throw new Error(
        `[codegraft] splitter '${splitter.id}' cannot be serialised: it must declare importName and importPath`,
      )
    }
    imports.push(`import { ${splitter.importName} } from '${splitter.importPath}'`)
    targetExpr = splitter.importName
  } else {
    targetExpr = JSON.stringify(target)
  }
  const opts = namespace === undefined ? '' : `, { namespace: ${JSON.stringify(namespace)} }`
  return [
    '// generated by codegraft build',
    ...imports,
    '',
    `export const transform = createCodemodTransformer(${targetExpr}, ${body}${opts})`,
    '',
  ].join('\n')
}
