import type { CompiledRule, GrammarId, ZoneSplitter } from '@trast/core'

/**
 * The `@trast/core` navigation helpers a rewrite may reference. `trast build` scans
 * each rewrite/guard source and imports only the ones used, so generated files never
 * pull helpers they don't need. (These are implemented in core's public API; until
 * then a rule referencing one fails the same way in dev mode.)
 */
const CORE_HELPERS = ['evaluate', 'getPropertySignatures', 'getPropertyName', 'getConditionalBranches']

/**
 * Emit an ES module source string for a target's compiled rules (§8). A rule is
 * emitted as **data plus one (or two) user functions**: the `PatternNode` as a JSON
 * literal, the comment gate as a `RegExp` literal, and the user-authored `rewrite`
 * (and optional `guard`) via `.toString()`. `createTransformer` reconstructs the
 * runtime visitor/predicate at load time — the emitted file never names any
 * matcher internals.
 */
export function serialiseRules(
  target: GrammarId | ZoneSplitter,
  rules: CompiledRule[],
  namespace?: string,
): string {
  const splitter = typeof target === 'string' ? null : target
  const coreImports = ['createTransformer', 'remove', ...usedHelpers(rules)]

  const imports = [`import { ${coreImports.join(', ')} } from '@trast/core'`]
  let targetExpr: string
  if (splitter) {
    const { importName, importPath } = splitter
    if (!importName || !importPath) {
      throw new Error(
        `[trast] splitter '${splitter.id}' cannot be serialised: it must declare importName and importPath`,
      )
    }
    imports.push(`import { ${importName} } from '${importPath}'`)
    targetExpr = importName
  } else {
    targetExpr = JSON.stringify(target)
  }

  const body = rules.map(serialiseRule).join(',\n')
  const tail = namespace === undefined ? '])' : `], ${JSON.stringify(namespace)})`
  return [
    '// generated by trast build',
    ...imports,
    '',
    `export const transform = createTransformer(${targetExpr}, [`,
    body,
    tail,
    '',
  ].join('\n')
}

function serialiseRule(rule: CompiledRule): string {
  const fields = [
    `language: ${JSON.stringify(rule.language)}`,
    `pattern: ${JSON.stringify(rule.pattern)}`,
    `guard: ${rule.guard ? rule.guard.toString() : 'null'}`,
    `commentRegex: ${rule.commentRegex ? rule.commentRegex.toString() : 'null'}`,
    `rewrite: ${rule.rewrite.toString()}`,
  ]
  return `  {\n    ${fields.join(',\n    ')},\n  }`
}

/** Helpers referenced (by name) in any rewrite or guard source. */
function usedHelpers(rules: CompiledRule[]): string[] {
  const source = rules
    .map((r) => r.rewrite.toString() + (r.guard ? r.guard.toString() : ''))
    .join('\n')
  return CORE_HELPERS.filter((name) => new RegExp(`\\b${name}\\b`).test(source))
}
